package plan

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func WriteHints(repoDir string, plan *Plan, request string) error {
	hintsPath := filepath.Join(repoDir, ".goosehints")

	var b strings.Builder
	b.WriteString("# AUTO-GENERATED by migration-harness\n")
	fmt.Fprintf(&b, "# %s | request: %s\n\n", time.Now().Format(time.RFC3339), request)

	b.WriteString("## TOKEN DISCIPLINE\n")
	b.WriteString("- Read ONE file at a time\n")
	b.WriteString("- After writing each file: STOP\n")
	b.WriteString("- Do NOT re-read migrated files\n")
	b.WriteString("- Do NOT compile unless explicitly asked\n\n")

	b.WriteString("## Migration\n")
	fmt.Fprintf(&b, "- Source: %s\n", plan.SourceStack)
	fmt.Fprintf(&b, "- Target: %s\n", plan.TargetStack)
	fmt.Fprintf(&b, "- Type:   %s\n\n", plan.MigrationType)

	b.WriteString("## Order\n")
	for _, item := range plan.Items {
		fmt.Fprintf(&b, "%d. [%s] %s  — %s\n", item.N, item.Action, item.Path, item.Notes)
	}
	b.WriteString("\n")

	b.WriteString("## Checklist\n")
	for _, item := range plan.Items {
		fmt.Fprintf(&b, "- [ ] %d. %s\n", item.N, item.Path)
	}

	return os.WriteFile(hintsPath, []byte(b.String()), 0644)
}

func UpdateHintsChecklist(repoDir string, itemN int) error {
	hintsPath := filepath.Join(repoDir, ".goosehints")
	data, err := os.ReadFile(hintsPath)
	if err != nil {
		return err
	}

	old := fmt.Sprintf("- [ ] %d.", itemN)
	new := fmt.Sprintf("- [x] %d.", itemN)
	content := strings.Replace(string(data), old, new, 1)

	return os.WriteFile(hintsPath, []byte(content), 0644)
}
